"""Insert curated rooftop events into Supabase."""
import os
from supabase import create_client

# Load env
with open('.env.local') as f:
    for line in f:
        if '=' in line and not line.startswith('#'):
            k, v = line.strip().split('=', 1)
            os.environ[k] = v

supabase = create_client(os.environ['NEXT_PUBLIC_SUPABASE_URL'], os.environ['SUPABASE_SERVICE_ROLE_KEY'])

events = [
    {"title": "MIKA - Spinning Out Tour", "date": "2026-05-02", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "Sold Out", "is_free": False, "url": "https://rooftopatpier17.com/events/mika-2026/", "description": "Pop sensation MIKA kicks off the Seaport Concert Series with Brooklyn Bridge skyline views.", "source": "manual_curated", "is_featured": False},
    {"title": "LASZEWO", "date": "2026-05-09", "time": "6:30 PM", "end_time": "10:30 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "Sold Out", "is_free": False, "url": "https://rooftopatpier17.com/events/laszewo-2026/", "description": "Project91 presents LASZEWO at the Seaport Concert Series.", "source": "manual_curated", "is_featured": False},
    {"title": "Bilmuri - Kinda Hard Tour", "date": "2026-05-15", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "Sold Out", "is_free": False, "url": "https://rooftopatpier17.com/events/bilmuri-2026/", "description": "Bilmuri brings the Kinda Hard Tour to the rooftop stage.", "source": "manual_curated", "is_featured": False},
    {"title": "Belle & Sebastian (Night 1)", "date": "2026-05-22", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "Sold Out", "is_free": False, "url": "https://rooftopatpier17.com/events/belle-and-sebastian-2025/", "description": "Scottish indie legends - two night run May 22-23.", "source": "manual_curated", "is_featured": False},
    {"title": "Belle & Sebastian (Night 2)", "date": "2026-05-23", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "Sold Out", "is_free": False, "url": "https://rooftopatpier17.com/events/belle-and-sebastian-2025/", "description": "Night two of Belle & Sebastian at Pier 17.", "source": "manual_curated", "is_featured": False},
    {"title": "Nate Smith - Country Rock and Roll Tour", "date": "2026-05-28", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$45+", "is_free": False, "url": "https://rooftopatpier17.com/events/nate-smith-2026/", "description": "Country star Nate Smith performs with the NYC skyline behind him.", "source": "manual_curated", "is_featured": False},
    {"title": "Iration - Where It All Began Tour", "date": "2026-05-29", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$40+", "is_free": False, "url": "https://rooftopatpier17.com/events/iration-2026/", "description": "Reggae-rock favorites Iration bring island vibes to the Seaport.", "source": "manual_curated", "is_featured": False},
    {"title": "Chet Faker - A Love For Strangers Tour", "date": "2026-05-30", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$69+", "is_free": False, "url": "https://rooftopatpier17.com/events/chet-faker-2026/", "description": "Electronic singer-songwriter Chet Faker performs at sunset.", "source": "manual_curated", "is_featured": False},
    {"title": "Turnpike Troubadours w/ Lucero", "date": "2026-06-05", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "Sold Out", "is_free": False, "url": "https://rooftopatpier17.com/events/turnpike-troubadours-2026/", "description": "Red dirt country kings with Lucero opening.", "source": "manual_curated", "is_featured": False},
    {"title": "Twinsick", "date": "2026-06-06", "time": "6:00 PM", "end_time": "10:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$35+", "is_free": False, "url": "https://rooftopatpier17.com/events/twinsick-2026/", "description": "Twinsick at the Seaport Concert Series.", "source": "manual_curated", "is_featured": False},
    {"title": "Tash Sultana - North American Tour", "date": "2026-06-07", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$70+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Multi-instrumentalist one-person-band spectacle on the waterfront.", "source": "manual_curated", "is_featured": True},
    {"title": "Lupe Fiasco - Food & Liquor 20th Anniversary", "date": "2026-06-10", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$70+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Lupe celebrates 20 years of Food & Liquor performed in full.", "source": "manual_curated", "is_featured": True},
    {"title": "The Warning", "date": "2026-06-11", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "Sold Out", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Mexican rock trio The Warning at the Seaport.", "source": "manual_curated", "is_featured": False},
    {"title": "moe. & Umphrey's McGee - moe.mentUM Tour", "date": "2026-06-12", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Jam band double header on the waterfront.", "source": "manual_curated", "is_featured": False},
    {"title": "Ty Meyers - The Legal Tour", "date": "2026-06-13", "time": "6:30 PM", "end_time": "10:30 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$35+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Ty Meyers at the Seaport Concert Series.", "source": "manual_curated", "is_featured": False},
    {"title": "Jimmy Eat World - 25 Years of Bleed American", "date": "2026-06-17", "time": "6:00 PM", "end_time": "10:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Jimmy Eat World plays Bleed American front to back on the waterfront.", "source": "manual_curated", "is_featured": True},
    {"title": "Young the Giant w/ Cold War Kids (Night 1)", "date": "2026-06-18", "time": "6:00 PM", "end_time": "10:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$55+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Victory Garden Tour double header.", "source": "manual_curated", "is_featured": False},
    {"title": "Young the Giant w/ Cold War Kids (Night 2)", "date": "2026-06-19", "time": "6:00 PM", "end_time": "10:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$55+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Night two of the Victory Garden Tour.", "source": "manual_curated", "is_featured": False},
    {"title": "Reggae Fest Blaze - Day Party", "date": "2026-06-20", "time": "3:00 PM", "end_time": "9:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$45+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Afternoon reggae vibes on the waterfront.", "source": "manual_curated", "is_featured": False},
    {"title": "The Breeders", "date": "2026-06-24", "time": "7:00 PM", "end_time": "11:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$55+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Alt-rock icons at the Seaport Concert Series.", "source": "manual_curated", "is_featured": False},
    {"title": "Dark Star Orchestra (Night 1)", "date": "2026-06-25", "time": "6:00 PM", "end_time": "10:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$77+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Grateful Dead tribute - two night run.", "source": "manual_curated", "is_featured": False},
    {"title": "Dark Star Orchestra (Night 2)", "date": "2026-06-26", "time": "6:00 PM", "end_time": "10:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$77+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "Night two of Dark Star Orchestra.", "source": "manual_curated", "is_featured": False},
    {"title": "Everyday People NYC - Day Party", "date": "2026-06-27", "time": "3:00 PM", "end_time": "9:00 PM", "venue": "The Rooftop at Pier 17", "address": "89 South St, Manhattan", "neighborhood": "Lower Manhattan", "category": "Rooftop", "cost": "$40+", "is_free": False, "url": "https://rooftopatpier17.com/line-up/", "description": "DJ mOma, Kendollaz - rooftop day party.", "source": "manual_curated", "is_featured": False},
    {"title": "Benny Benassi - Album Release", "date": "2026-05-02", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$75+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Electro house legend 100 stories above Manhattan. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Kaz James", "date": "2026-05-08", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Deep house 100 stories up. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Layla Benitez", "date": "2026-05-09", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Highest nightclub in NYC. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Agents of Time", "date": "2026-05-15", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Melodic techno 1,100 feet above Manhattan. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "ARODES", "date": "2026-05-16", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "ARODES at Marquee Skydeck. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Lilya Mandre", "date": "2026-05-22", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Lilya Mandre. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Gareth Emery", "date": "2026-05-23", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$70+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Trance legend. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "MK", "date": "2026-05-24", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$75+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "House music icon MK 100 stories up. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Antdot", "date": "2026-05-29", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Brazilian house producer. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Joel Corry", "date": "2026-05-30", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$75+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "UK dance hitmaker. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Kozlow x Tolga x Orson", "date": "2026-06-05", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$60+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Triple DJ bill. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Tripolism", "date": "2026-06-13", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$65+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Tripolism at Marquee Skydeck. 21+.", "source": "manual_curated", "is_featured": False},
    {"title": "Bob Moses (Club Set)", "date": "2026-06-19", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$75+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Melodic house duo DJ set 100 stories up. 21+.", "source": "manual_curated", "is_featured": True},
    {"title": "Hot Since 82", "date": "2026-06-26", "time": "11:00 PM", "end_time": "3:00 AM", "venue": "Marquee Skydeck at Edge", "address": "30 Hudson Yards, 100th Floor", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "$70+", "is_free": False, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "UK house maestro high above Manhattan. 21+.", "source": "manual_curated", "is_featured": True},
    {"title": "Kentucky Derby Party", "date": "2026-05-02", "time": "2:00 PM", "end_time": "11:30 PM", "venue": "230 Fifth Rooftop", "address": "230 5th Ave, Flatiron", "neighborhood": "Flatiron", "category": "Rooftop", "cost": "$30+", "is_free": False, "url": "https://230-fifth.com/", "description": "Watch the Derby with Empire State Building views.", "source": "manual_curated", "is_featured": False},
    {"title": "SOLUNA Day Party", "date": "2026-05-03", "time": "3:00 PM", "end_time": "10:00 PM", "venue": "230 Fifth Rooftop", "address": "230 5th Ave, Flatiron", "neighborhood": "Flatiron", "category": "Rooftop", "cost": "$25+", "is_free": False, "url": "https://230-fifth.com/", "description": "Sunset social on NYC largest rooftop bar.", "source": "manual_curated", "is_featured": False},
    {"title": "Cinco de Mayo Rooftop Meetup", "date": "2026-05-05", "time": "6:30 PM", "end_time": "11:30 PM", "venue": "230 Fifth Rooftop", "address": "230 5th Ave, Flatiron", "neighborhood": "Flatiron", "category": "Rooftop", "cost": "$25+", "is_free": False, "url": "https://www.eventbrite.com/e/cinco-de-mayo-international-rooftop-meetup-nyc-tickets-1987899761700", "description": "Sunset social for travelers, expats, and locals.", "source": "manual_curated", "is_featured": False},
    {"title": "Manhattan Mehfil: Bollywood Sufi Night", "date": "2026-05-09", "time": "10:00 PM", "end_time": "3:00 AM", "venue": "230 Fifth Rooftop", "address": "230 5th Ave, Flatiron", "neighborhood": "Flatiron", "category": "Rooftop", "cost": "$30+", "is_free": False, "url": "https://230-fifth.com/", "description": "Live Bollywood and Sufi music with skyline views.", "source": "manual_curated", "is_featured": False},
    {"title": "Mothers Day Brunch Buffet", "date": "2026-05-10", "time": "10:00 AM", "end_time": "3:00 PM", "venue": "230 Fifth Rooftop", "address": "230 5th Ave, Flatiron", "neighborhood": "Flatiron", "category": "Rooftop", "cost": "$55+", "is_free": False, "url": "https://230-fifth.com/", "description": "Brunch buffet with rooftop skyline views.", "source": "manual_curated", "is_featured": False},
    {"title": "El DeBarge - Mothers Day Weekend Concert", "date": "2026-05-15", "time": "5:00 PM", "end_time": "11:00 PM", "venue": "INKwell Harbor Club Rooftop", "address": "Manhattan", "neighborhood": "Manhattan", "category": "Rooftop", "cost": "$85+", "is_free": False, "url": "https://www.eventbrite.com/e/el-debarge-mothers-day-weekend-special-live-at-the-inkwell-rooftop-nyc-tickets-1982555773688", "description": "R&B legend live. DJ Art Cross + Funk Flex. VIP includes Moet.", "source": "manual_curated", "is_featured": False},
    {"title": "Fleet Week Parade of Ships Viewing", "date": "2026-05-21", "time": "11:00 AM", "end_time": "1:00 PM", "venue": "Edge NYC, 100th Floor", "address": "30 Hudson Yards", "neighborhood": "Hudson Yards", "category": "Rooftop", "cost": "Free", "is_free": True, "url": "https://www.edgenyc.com/marquee-skydeck/", "description": "Watch the Parade of Ships from 100 stories up. Free coffee + bagel.", "source": "manual_curated", "is_featured": True},
    {"title": "Juneteenth Freedom Rooftop Party", "date": "2026-06-19", "time": "9:00 PM", "end_time": "3:00 AM", "venue": "276 Belmont Ave Rooftop", "address": "276 Belmont Ave, Brooklyn", "neighborhood": "Brooklyn", "category": "Rooftop", "cost": "$25+", "is_free": False, "url": "https://www.eventbrite.com/e/junteenth-freedom-rooftop-party-in-nyc-tickets-1985722120316", "description": "Celebrate Juneteenth with Hip Hop, R&B, Reggae on a Brooklyn rooftop.", "source": "manual_curated", "is_featured": False},
]

created = 0
errors = 0
for ev in events:
    try:
        supabase.table("events").upsert(ev, on_conflict="title,date,venue").execute()
        created += 1
    except Exception as e:
        errors += 1
        if errors <= 3:
            print(f"Error: {ev['title'][:40]}: {e}")

print(f"Upserted: {created}")
print(f"Errors: {errors}")

result = supabase.table("events").select("id", count="exact").eq("category", "Rooftop").execute()
print(f"Rooftop events in database: {result.count}")

result2 = supabase.table("events").select("id", count="exact").execute()
print(f"Total events in database: {result2.count}")
